site_name: Shared Security Responsibility Model (SSRM)
repo_url: https://github.com/trustsource/SSRM
edit_uri: ""    # prevents the edit button to link into URL
theme:
  name: material
  font: false # set false, to comply with data privacy (google fonts)
  #  text: Open Sans
  #  code: Courier
  logo: assets/TS_logo_lang.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.expand 
    - navigatin.top
    # - header.autohide 
  extra_css:
    - assets/stylesheet.css

extra:
  homepage: https://www.trustsource.io
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better. 
    cookies:
      analytics: 
        name: Google Analytics
        checked: false
    actions:
      - accept
      - manage
      - reject
  analytics:
    provider: google
    property: G-xxx
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
           Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
           Thanks for your feedback! Help us improve this page by
           using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/trustsource
      name: TrustSource @ Linkedin
  #  plugins:
#    - social
#        cards: !ENV [CARDS, false]          

copyright: Copyright &copy; 2022 EACG GmbH
